// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends Plugin<infer T> ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.4.6_typescript@4.9.5_vue@3.2.45/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3").default> &
  InjectionType<typeof import("../components.plugin").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.1.1_eslint@8.33.0_sass@1.57.1_typescript@4.9.5/node_modules/nuxt/dist/head/runtime/lib/vueuse-head.plugin").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.1.1_eslint@8.33.0_sass@1.57.1_typescript@4.9.5/node_modules/nuxt/dist/pages/runtime/plugins/router").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.1.1_eslint@8.33.0_sass@1.57.1_typescript@4.9.5/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+supabase@0.3.1/node_modules/@nuxtjs/supabase/dist/runtime/plugins/auth-redirect").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+supabase@0.3.1/node_modules/@nuxtjs/supabase/dist/runtime/plugins/supabase.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+supabase@0.3.1/node_modules/@nuxtjs/supabase/dist/runtime/plugins/supabase.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@8.0.0-beta.8_vue@3.2.45/node_modules/@nuxtjs/i18n/dist/runtime/plugins/composition").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@8.0.0-beta.8_vue@3.2.45/node_modules/@nuxtjs/i18n/dist/runtime/plugins/i18n").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+image-edge@1.0.0-27840416.dc1ed65/node_modules/@nuxt/image-edge/dist/runtime/plugin").default> &
  InjectionType<typeof import("../../plugins/sweetalert").default>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
